export type StateEntry = {
  name: string;
  slug: string;
  abbr: string;
  agency: string;
  searchUrl: string;
  agencyUrl: string;
  notes?: string;
};

// Canonical Secretary of State (or equivalent) business-entity search endpoints.
// URLs are on official .gov / state domains. If any URL is updated by the agency,
// change it here — every page, card, and sitemap entry is generated from this file.
export const STATES: StateEntry[] = [
  {
    name: "Alabama",
    slug: "alabama",
    abbr: "AL",
    agency: "Alabama Secretary of State",
    searchUrl: "https://arc-sos.state.al.us/cgi/corpname.mbr/input",
    agencyUrl: "https://www.sos.alabama.gov/",
  },
  {
    name: "Alaska",
    slug: "alaska",
    abbr: "AK",
    agency: "Alaska Division of Corporations, Business & Professional Licensing",
    searchUrl: "https://www.commerce.alaska.gov/cbp/main/search/entities",
    agencyUrl: "https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx",
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbr: "AZ",
    agency: "Arizona Corporation Commission",
    searchUrl: "https://ecorp.azcc.gov/EntitySearch/Index",
    agencyUrl: "https://azcc.gov/corporations",
    notes: "Arizona uses the Corporation Commission, not the Secretary of State, for business filings.",
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbr: "AR",
    agency: "Arkansas Secretary of State",
    searchUrl: "https://www.sos.arkansas.gov/corps/search_corps.php",
    agencyUrl: "https://www.sos.arkansas.gov/business-commercial-services-bcs",
  },
  {
    name: "California",
    slug: "california",
    abbr: "CA",
    agency: "California Secretary of State (bizfile Online)",
    searchUrl: "https://bizfileonline.sos.ca.gov/search/business",
    agencyUrl: "https://www.sos.ca.gov/business-programs",
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbr: "CO",
    agency: "Colorado Secretary of State",
    searchUrl: "https://www.coloradosos.gov/biz/BusinessEntityCriteriaExt.do",
    agencyUrl: "https://www.coloradosos.gov/biz/",
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbr: "CT",
    agency: "Connecticut Secretary of the State",
    searchUrl: "https://service.ct.gov/business/s/onlinebusinesssearch",
    agencyUrl: "https://portal.ct.gov/sots",
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbr: "DE",
    agency: "Delaware Division of Corporations",
    searchUrl: "https://icis.corp.delaware.gov/ecorp/entitysearch/NameSearch.aspx",
    agencyUrl: "https://corp.delaware.gov/",
  },
  {
    name: "District of Columbia",
    slug: "district-of-columbia",
    abbr: "DC",
    agency: "DC Department of Licensing and Consumer Protection",
    searchUrl: "https://corponline.dlcp.dc.gov/BizEntity.aspx/StartSearch",
    agencyUrl: "https://dlcp.dc.gov/page/corporations-division",
  },
  {
    name: "Florida",
    slug: "florida",
    abbr: "FL",
    agency: "Florida Division of Corporations (Sunbiz)",
    searchUrl: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
    agencyUrl: "https://dos.fl.gov/sunbiz/",
  },
  {
    name: "Georgia",
    slug: "georgia",
    abbr: "GA",
    agency: "Georgia Secretary of State (Corporations Division)",
    searchUrl: "https://ecorp.sos.ga.gov/BusinessSearch",
    agencyUrl: "https://sos.ga.gov/corporations-division",
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbr: "HI",
    agency: "Hawaii Department of Commerce and Consumer Affairs (Business Registration Division)",
    searchUrl: "https://hbe.ehawaii.gov/documents/search.html",
    agencyUrl: "https://cca.hawaii.gov/breg/",
  },
  {
    name: "Idaho",
    slug: "idaho",
    abbr: "ID",
    agency: "Idaho Secretary of State",
    searchUrl: "https://sosbiz.idaho.gov/search/business",
    agencyUrl: "https://sos.idaho.gov/business-entities/",
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbr: "IL",
    agency: "Illinois Secretary of State",
    searchUrl: "https://apps.ilsos.gov/businessentitysearch/",
    agencyUrl: "https://www.ilsos.gov/departments/business_services/home.html",
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbr: "IN",
    agency: "Indiana Secretary of State (INBiz)",
    searchUrl: "https://bsd.sos.in.gov/publicbusinesssearch",
    agencyUrl: "https://inbiz.in.gov/",
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbr: "IA",
    agency: "Iowa Secretary of State",
    searchUrl: "https://sos.iowa.gov/search/business/search.aspx",
    agencyUrl: "https://sos.iowa.gov/business/",
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbr: "KS",
    agency: "Kansas Secretary of State",
    searchUrl: "https://www.sos.ks.gov/businesses/business_entity_search.aspx",
    agencyUrl: "https://www.sos.ks.gov/businesses/businesses.html",
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbr: "KY",
    agency: "Kentucky Secretary of State",
    searchUrl: "https://web.sos.ky.gov/ftsearch/",
    agencyUrl: "https://www.sos.ky.gov/bus/Pages/default.aspx",
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbr: "LA",
    agency: "Louisiana Secretary of State (Commercial Division)",
    searchUrl: "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx",
    agencyUrl: "https://www.sos.la.gov/BusinessServices/",
  },
  {
    name: "Maine",
    slug: "maine",
    abbr: "ME",
    agency: "Maine Secretary of State (Bureau of Corporations)",
    searchUrl: "https://icrs.informe.org/nei-sos-icrs/ICRS",
    agencyUrl: "https://www.maine.gov/sos/cec/corp/",
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbr: "MD",
    agency: "Maryland Department of Assessments and Taxation",
    searchUrl: "https://egov.maryland.gov/businessexpress/entitysearch",
    agencyUrl: "https://dat.maryland.gov/businesses/",
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbr: "MA",
    agency: "Massachusetts Secretary of the Commonwealth",
    searchUrl: "https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx",
    agencyUrl: "https://www.sec.state.ma.us/divisions/corporations/corporations.htm",
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbr: "MI",
    agency: "Michigan Department of Licensing and Regulatory Affairs (LARA)",
    searchUrl: "https://cofs.lara.state.mi.us/SearchApi/Search/Search",
    agencyUrl: "https://www.michigan.gov/lara/bureau-list/cscl",
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbr: "MN",
    agency: "Minnesota Secretary of State",
    searchUrl: "https://mblsportal.sos.state.mn.us/Business/Search",
    agencyUrl: "https://www.sos.state.mn.us/business-liens/",
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbr: "MS",
    agency: "Mississippi Secretary of State",
    searchUrl: "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
    agencyUrl: "https://www.sos.ms.gov/business-services",
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbr: "MO",
    agency: "Missouri Secretary of State",
    searchUrl: "https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx?SearchType=0",
    agencyUrl: "https://www.sos.mo.gov/business",
  },
  {
    name: "Montana",
    slug: "montana",
    abbr: "MT",
    agency: "Montana Secretary of State",
    searchUrl: "https://biz.sosmt.gov/search/business",
    agencyUrl: "https://sosmt.gov/business/",
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbr: "NE",
    agency: "Nebraska Secretary of State",
    searchUrl: "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
    agencyUrl: "https://sos.nebraska.gov/business-services",
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbr: "NV",
    agency: "Nevada Secretary of State",
    searchUrl: "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
    agencyUrl: "https://www.nvsos.gov/sos/businesses",
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbr: "NH",
    agency: "New Hampshire Secretary of State",
    searchUrl: "https://quickstart.sos.nh.gov/online/BusinessInquire",
    agencyUrl: "https://www.sos.nh.gov/corporations-ucc-securities",
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbr: "NJ",
    agency: "New Jersey Department of the Treasury (Division of Revenue)",
    searchUrl: "https://www.njportal.com/DOR/BusinessNameSearch/",
    agencyUrl: "https://www.nj.gov/treasury/revenue/",
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbr: "NM",
    agency: "New Mexico Secretary of State",
    searchUrl: "https://enterprise.sos.nm.gov/search",
    agencyUrl: "https://www.sos.nm.gov/business-services/",
  },
  {
    name: "New York",
    slug: "new-york",
    abbr: "NY",
    agency: "New York Department of State (Division of Corporations)",
    searchUrl: "https://apps.dos.ny.gov/publicInquiry/",
    agencyUrl: "https://dos.ny.gov/division-corporations",
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbr: "NC",
    agency: "North Carolina Secretary of State",
    searchUrl: "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
    agencyUrl: "https://www.sosnc.gov/divisions/business_registration",
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbr: "ND",
    agency: "North Dakota Secretary of State (FirstStop)",
    searchUrl: "https://firststop.sos.nd.gov/search",
    agencyUrl: "https://sos.nd.gov/business",
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbr: "OH",
    agency: "Ohio Secretary of State",
    searchUrl: "https://businesssearch.ohiosos.gov/",
    agencyUrl: "https://www.ohiosos.gov/businesses/",
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbr: "OK",
    agency: "Oklahoma Secretary of State",
    searchUrl: "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
    agencyUrl: "https://www.sos.ok.gov/business/",
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbr: "OR",
    agency: "Oregon Secretary of State (Corporation Division)",
    searchUrl: "https://sos.oregon.gov/business/Pages/find.aspx",
    agencyUrl: "https://sos.oregon.gov/business/Pages/default.aspx",
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbr: "PA",
    agency: "Pennsylvania Department of State (Bureau of Corporations)",
    searchUrl: "https://www.corporations.pa.gov/search/corpsearch",
    agencyUrl: "https://www.dos.pa.gov/BusinessCharities/Pages/default.aspx",
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbr: "RI",
    agency: "Rhode Island Department of State",
    searchUrl: "https://business.sos.ri.gov/corpweb/corpsearch/corpsearch.aspx",
    agencyUrl: "https://www.sos.ri.gov/divisions/business-services",
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbr: "SC",
    agency: "South Carolina Secretary of State",
    searchUrl: "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
    agencyUrl: "https://sos.sc.gov/online-filings/business-entities",
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbr: "SD",
    agency: "South Dakota Secretary of State",
    searchUrl: "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
    agencyUrl: "https://sosenterprise.sd.gov/BusinessServices/",
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbr: "TN",
    agency: "Tennessee Secretary of State",
    searchUrl: "https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx",
    agencyUrl: "https://sos.tn.gov/business-services",
  },
  {
    name: "Texas",
    slug: "texas",
    abbr: "TX",
    agency: "Texas Comptroller (Taxable Entity Search)",
    searchUrl: "https://mycpa.cpa.state.tx.us/coa/",
    agencyUrl: "https://www.sos.state.tx.us/corp/",
    notes: "Texas's free public entity lookup is hosted by the Comptroller. Full SOSDirect access at the Secretary of State requires a paid account.",
  },
  {
    name: "Utah",
    slug: "utah",
    abbr: "UT",
    agency: "Utah Division of Corporations and Commercial Code",
    searchUrl: "https://secure.utah.gov/bes/",
    agencyUrl: "https://corporations.utah.gov/",
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbr: "VT",
    agency: "Vermont Secretary of State",
    searchUrl: "https://bizfilings.vermont.gov/online/BusinessInquire",
    agencyUrl: "https://sos.vermont.gov/corporations/",
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbr: "VA",
    agency: "Virginia State Corporation Commission (Clerk's Information System)",
    searchUrl: "https://cis.scc.virginia.gov/EntitySearch/Index",
    agencyUrl: "https://www.scc.virginia.gov/pages/Businesses",
  },
  {
    name: "Washington",
    slug: "washington",
    abbr: "WA",
    agency: "Washington Secretary of State (Corporations & Charities Filing System)",
    searchUrl: "https://ccfs.sos.wa.gov/#/BusinessSearch/BusinessInformation",
    agencyUrl: "https://www.sos.wa.gov/corporations-charities",
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbr: "WV",
    agency: "West Virginia Secretary of State",
    searchUrl: "https://apps.sos.wv.gov/business/corporations/",
    agencyUrl: "https://sos.wv.gov/business-licensing",
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbr: "WI",
    agency: "Wisconsin Department of Financial Institutions",
    searchUrl: "https://www.wdfi.org/apps/CorpSearch/Search.aspx",
    agencyUrl: "https://www.wdfi.org/corporations/",
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbr: "WY",
    agency: "Wyoming Secretary of State",
    searchUrl: "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
    agencyUrl: "https://sos.wyo.gov/business/",
  },
];

export function getStateBySlug(slug: string): StateEntry | undefined {
  return STATES.find((s) => s.slug === slug);
}

export function getAllSlugs(): string[] {
  return STATES.map((s) => s.slug);
}
